### GET Method
GET http://localhost:8000/api/v1/users

### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "task":"Eating",
    "hours": 5
    
}

###PATCH Method
PATCH http://localhost:8000/api/v1/users/
Content-Type: application/json

{
    "_id": "67b3307ac3ca631a1fadf1c5",
    
    "type":"bad"
}

### Delete Method
DELETE http://localhost:8000/api/v1/users/
Content-Type: application/json

[
   "67b8559e9db5292fc3740691","67b855d39db5292fc37406a2"
]
