### GET Method
GET http://localhost:8000/api/v1/users

### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "fName":"Adamghat",
    "lName":"Dhading"
}

###PATCH Method
PATCH http://localhost:8000/api/v1/users/
Content-Type: application/json

{
    "_id": "67b31f6e4c293a1000dad319",
    "fName":"Sanjay",
    "lName":"Karki"
}

### Delete Method
DELETE http://localhost:8000/api/v1/users/67b3267622e8693a7c1bc990
