### GET Method
GET http://localhost:8000/api/v1/users

### POST Method
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "task":"Playing",
    "hr":"70",
    "type":"bad"
}

###PATCH Method
PATCH http://localhost:8000/api/v1/users/
Content-Type: application/json

{
    "_id": "67b3307ac3ca631a1fadf1c5",
    
    "type":"entry"
}

### Delete Method
DELETE http://localhost:8000/api/v1/users/67b330c67782ca7f612dc508
